baseURL = 'https://example.org/'
locale = 'zh-CN'
title = 'Example Blog'
theme = 'hugo-theme-yu'
summaryLength = 36

[params]
lang = 'zh-CN'
description = 'A Hugo example site'
author = 'Example Author'
footer = '© 2026 Example Author'
mainSections = ['posts']
projectsURL = '/projects/'

[outputs]
home = ['HTML', 'RSS', 'JSON']

[taxonomies]
tag = 'tags'
category = 'categories'
